CREATE SEQUENCE SEQ_MEM;

CREATE TABLE TBL_MEM(
   NUM NUMBER PRIMARY KEY,
   ID VARCHAR2(1000) UNIQUE NOT NULL,
   PASSWORD VARCHAR2(1000) NOT NULL,
   NAME VARCHAR2(1000) NOT NULL,
   EMAIL VARCHAR2(1000) NOT NULL,
   BIRTHDAY DATE
);

DROP TABLE TBL_MEM;



SELECT *FROM TBL_MEM;
